dist: trusty
sudo: required
language: cpp
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev
 - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
 - sudo tar xf release-1.7.0.tar.gz
 - cd googletest-release-1.7.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"
 - wget https://github.com/opentrv/OTAESGCM/archive/master.zip
 - unzip master.zip
script: ./PortableUnitTestsDriver.sh
notifications:
  email:
    recipients:
      - ci@opentrv.uk
    on_success: change
    on_failure: always
  irc:
    channels: "irc.z.je#opentrv"
    on_success: change
    on_failure: change

